declare enum PingType {
    Normal,
    Normal2,
    DangerRed,
    Missing,
    OnMyWay,
    DangerYellow,
    AssistMe,
    AreaIsWarded,
    MinimapWhite,
    MinimapRed,
    MinimapGreenDot,
    MinimapBlueDot,
    MinimapRedDot,
}
